[2023-10-11 13:49:38,115] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: job_posting_aggregator.transform_linkedin 2023-10-11T13:49:02.881428+00:00 [queued]>
[2023-10-11 13:49:38,144] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: job_posting_aggregator.transform_linkedin 2023-10-11T13:49:02.881428+00:00 [queued]>
[2023-10-11 13:49:38,146] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 13:49:38,148] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2023-10-11 13:49:38,153] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 13:49:38,174] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): transform_linkedin> on 2023-10-11T13:49:02.881428+00:00
[2023-10-11 13:49:38,185] {standard_task_runner.py:52} INFO - Started process 5082 to run task
[2023-10-11 13:49:38,197] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'job_posting_aggregator', 'transform_linkedin', '2023-10-11T13:49:02.881428+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_jobs_data.py', '--cfg-path', '/tmp/tmptvo9sx2b', '--error-file', '/tmp/tmpemnjc0qu']
[2023-10-11 13:49:38,199] {standard_task_runner.py:77} INFO - Job 28: Subtask transform_linkedin
[2023-10-11 13:49:38,280] {logging_mixin.py:104} INFO - Running <TaskInstance: job_posting_aggregator.transform_linkedin 2023-10-11T13:49:02.881428+00:00 [running]> on host 62cfcfb44bb5
[2023-10-11 13:49:38,361] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=you
AIRFLOW_CTX_DAG_ID=job_posting_aggregator
AIRFLOW_CTX_TASK_ID=transform_linkedin
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T13:49:02.881428+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T13:49:02.881428+00:00
[2023-10-11 13:49:38,417] {get_jobs_data.py:372} INFO - 1 month ago
[2023-10-11 13:49:40,490] {get_jobs_data.py:372} INFO - 1 month ago
[2023-10-11 13:49:40,528] {get_jobs_data.py:372} INFO - 3 months ago
[2023-10-11 13:49:40,569] {get_jobs_data.py:252} INFO - Error detecting language. Error: expected string or bytes-like object
[2023-10-11 13:49:40,571] {get_jobs_data.py:372} INFO - 1 month ago
[2023-10-11 13:49:40,603] {get_jobs_data.py:372} INFO - 1 month ago
[2023-10-11 13:49:40,643] {get_jobs_data.py:372} INFO - 1 month ago
[2023-10-11 13:49:40,681] {get_jobs_data.py:252} INFO - Error detecting language. Error: expected string or bytes-like object
[2023-10-11 13:49:40,683] {get_jobs_data.py:372} INFO - 1 month ago
[2023-10-11 13:49:40,719] {get_jobs_data.py:372} INFO - 1 month ago
[2023-10-11 13:49:40,762] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_jobs_data.py", line 445, in transform_linkedin_jobs
    transformer.run_all()
  File "/opt/airflow/dags/get_jobs_data.py", line 308, in run_all
    self.save_jobs(data_clean)
  File "/opt/airflow/dags/get_jobs_data.py", line 302, in save_jobs
    with open(file_name, "w") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/processed/linkedin_json/linkedin_cleaned_data.json'
[2023-10-11 13:49:40,773] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=job_posting_aggregator, task_id=transform_linkedin, execution_date=20231011T134902, start_date=20231011T134938, end_date=20231011T134940
[2023-10-11 13:49:40,865] {local_task_job.py:151} INFO - Task exited with return code 1
