[2023-10-11 11:04:38,346] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test_utils.sleeps_forever 2023-10-11T11:04:07+00:00 [queued]>
[2023-10-11 11:04:38,370] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test_utils.sleeps_forever 2023-10-11T11:04:07+00:00 [queued]>
[2023-10-11 11:04:38,371] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 11:04:38,373] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2023-10-11 11:04:38,375] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 11:04:38,386] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): sleeps_forever> on 2023-10-11T11:04:07+00:00
[2023-10-11 11:04:38,394] {standard_task_runner.py:52} INFO - Started process 56345 to run task
[2023-10-11 11:04:38,400] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_utils', 'sleeps_forever', '2023-10-11T11:04:07+00:00', '--job-id', '19', '--pool', 'default_pool', '--raw', '--subdir', '/home/***/.local/lib/python3.6/site-packages/***/example_dags/test_utils.py', '--cfg-path', '/tmp/tmpg_etbcsf', '--error-file', '/tmp/tmpxqsffmpb']
[2023-10-11 11:04:38,404] {standard_task_runner.py:77} INFO - Job 19: Subtask sleeps_forever
[2023-10-11 11:04:38,473] {logging_mixin.py:104} INFO - Running <TaskInstance: test_utils.sleeps_forever 2023-10-11T11:04:07+00:00 [running]> on host add09587d53f
[2023-10-11 11:04:38,622] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_utils
AIRFLOW_CTX_TASK_ID=sleeps_forever
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T11:04:07+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T11:04:07+00:00
[2023-10-11 11:04:38,628] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2023-10-11 11:04:38,634] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 10000000000']
[2023-10-11 11:04:38,672] {subprocess.py:75} INFO - Output:
[2023-10-11 11:12:18,202] {local_task_job.py:76} ERROR - Received SIGTERM. Terminating subprocesses
[2023-10-11 11:12:20,849] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 56345
[2023-10-11 11:12:21,432] {taskinstance.py:1284} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-10-11 11:12:21,491] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2023-10-11 11:12:21,876] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 175, in execute
    output_encoding=self.output_encoding,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/subprocess.py", line 77, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1286, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-10-11 11:12:21,943] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=test_utils, task_id=sleeps_forever, execution_date=20231011T110407, start_date=20231011T110438, end_date=20231011T111221
